services:
  - type: web
    name: touchgrass-backend
    env: node
    rootDir: backend
    buildCommand: npm install
    startCommand: node api/index.js
    envVars:
      - key: PORT
        value: 10000
      - key: FRONTEND_URL
        value: https://touchgrass.entrext.com
    plan: free
